version: '3.7'
services:
  db:
    image: 'library/postgres:16-alpine'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: 'interactive_tree'
      POSTGRES_USER: 'my_user@123'
      POSTGRES_PASSWORD: 'my_password@123456'
    restart: always

  rails:
    build: ./
    ports:
      - '3000:3000'
    volumes:
      - .:/docker/app # add our local code to dockerfile
    depends_on:
      - db  # add all dependant container
    environment:
      DB_HOST: db
      DB_NAME: 'interactive_tree'
      DB_USERNAME: 'my_user@123'
      DB_PASSWORD: 'my_password@123456'

volumes:
  postgres: # named volume
